image:
  repository: ghcr.io/centralmind/gateway
  tag: "0.0.0-rc3"

imagePullSecrets:
 - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  kind: IngressRoute
  entryPoints:
    - web
  hosts:
    - host: demo-gw.centralmind.ai
      paths:
        - path: /
          pathType: Prefix


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

gateway:
  api:
    name: Awesome Readonly API
    description: ""
    version: "1.0"
  database:
    type: postgres
    connection: |
      hosts:
        - postgres-postgresql
      user: postgres
      password: password
      database: mydb
      port: 5432
    tables:
      - name: gachi_teams
        columns:
          - name: id
            type: integer
            primary_key: false
          - name: team_name
            type: character varying
            primary_key: false
          - name: motto
            type: character varying
            primary_key: false
        endpoints:
          - http_method: GET
            http_path: /gachi_teams
            mcp_method: list_gachi_teams
            summary: Retrieves a paginated list of teams.
            description: 'This endpoint retrieves a list of teams with pagination. Example usage: /gachi_teams?offset=0&limit=10.'
            query: SELECT id, team_name, motto FROM gachi_teams ORDER BY id ASC OFFSET :offset LIMIT :limit
            params:
              - name: offset
                type: number
                location: query
                required: false
                default: 0
              - name: limit
                type: number
                location: query
                required: false
                default: 10
          - http_method: GET
            http_path: /gachi_teams/total_count
            mcp_method: count_gachi_teams
            summary: Retrieves total count of teams.
            description: 'This endpoint returns the total count of teams. Example usage: /gachi_teams/total_count.'
            query: SELECT COUNT(*) AS total_count FROM gachi_teams
            params: [ ]
          - http_method: GET
            http_path: /gachi_teams/{id}
            mcp_method: get_gachi_team
            summary: Retrieves details of a specific team.
            description: 'This endpoint retrieves details of a team by its id. Example usage: /gachi_teams/1.'
            query: SELECT id, team_name, motto FROM gachi_teams WHERE id = :id LIMIT 1
            params:
              - name: id
                type: number
                location: path
                required: true
      - name: gachi_personas
        columns:
          - name: strength_level
            type: integer
            primary_key: false
          - name: id
            type: integer
            primary_key: false
          - name: team_id
            type: integer
            primary_key: false
          - name: battle_cry
            type: character varying
            primary_key: false
          - name: special_move
            type: character varying
            primary_key: false
          - name: name
            type: character varying
            primary_key: false
          - name: favorite_drink
            type: character varying
            primary_key: false
        endpoints:
          - http_method: GET
            http_path: /gachi_personas
            mcp_method: list_gachi_personas
            summary: Retrieves a paginated list of personas.
            description: 'This endpoint retrieves a list of personas with pagination. Example usage: /gachi_personas?offset=0&limit=10.'
            query: SELECT strength_level, id, team_id, battle_cry, special_move, name, favorite_drink FROM gachi_personas ORDER BY id ASC OFFSET :offset LIMIT :limit
            params:
              - name: offset
                type: number
                location: query
                required: false
                default: 0
              - name: limit
                type: number
                location: query
                required: false
                default: 10
          - http_method: GET
            http_path: /gachi_personas/total_count
            mcp_method: count_gachi_personas
            summary: Retrieves total count of personas.
            description: 'This endpoint returns the total count of personas. Example usage: /gachi_personas/total_count.'
            query: SELECT COUNT(*) AS total_count FROM gachi_personas
            params: [ ]
          - http_method: GET
            http_path: /gachi_personas/{id}
            mcp_method: get_gachi_persona
            summary: Retrieves details of a specific persona.
            description: 'This endpoint retrieves details of a persona by its id. Example usage: /gachi_personas/1.'
            query: SELECT strength_level, id, team_id, battle_cry, special_move, name, favorite_drink FROM gachi_personas WHERE id = :id LIMIT 1
            params:
              - name: id
                type: number
                location: path
                required: true
  plugins:
    lru_cache:
      max_size: 1024
      ttl: 15s

