name: Run Build and Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - shell: bash
        run: |
          make build

  e2e-tests:
    needs: build
    name: tests / ${{ matrix.suite.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [
          { group: "connectors", name: "clickhouse", path: "clickhouse" },
          { group: "connectors", name: "postgres", path: "postgres" },
          { group: "connectors", name: "mysql", path: "mysql" },
          { group: "connectors", name: "snowflake", path: "snowflake" },
          { group: "connectors", name: "bigquery", path: "bigquery" },
          { group: "connectors", name: "mongodb", path: "mongodb" },
          { group: "plugins", name: "plugins", path: "..." },
          { group: "mcp", name: "mcp", path: "..." },
          { group: "server", name: "server", path: "..." },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - shell: bash
        run: |
          go install gotest.tools/gotestsum@latest
      - shell: bash
        run: |
          echo "Running ${{ matrix.suite.group }} suite ${{ matrix.suite.name }}"
          export RECIPE_CLICKHOUSE_BIN=clickhouse
          export USE_TESTCONTAINERS=1
          gotestsum \
            --junitfile="reports/${{ matrix.suite.name }}.xml" \
            --junitfile-project-name="${{ matrix.suite.group }}" \
            --junitfile-testsuite-name="short" \
            --rerun-fails \
            --format github-actions \
            --packages="./${{ matrix.suite.group }}/${{ matrix.suite.path }}" \
            -- -timeout=15m
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.suite.name }}
          path: reports/*.xml
      - name: Fail if tests failed
        if: failure()
        run: exit 1

  test-report:
    needs: [e2e-tests]
    name: test-report
    if: always() && !contains(needs.*.result, 'skipped')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download All Test Reports
        uses: actions/download-artifact@v4
        with:
          pattern: test-reports-*
          merge-multiple: true
          path: reports/
      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "reports/*.xml"
