name: Auto build and publish of gateway image

on:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*.*.*'

jobs:
  trigger-build:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ github.ref_name }}

