name: Auto build and publish of gateway for PR

on:
  pull_request:
    branches:
      - "*"

jobs:
  trigger-build-pr:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      version: '${{ github.event.pull_request.number }}'
      extra_args: '--snapshot'

