name: Release Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'helm/gateway/**'

  pull_request:
    paths:
      - 'helm/gateway/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package helm
        env:
          GITHUB_USERNAME: laskoviymishka
          GHCR_TOKEN: ${{ secrets.GH_HELM_PAT }}
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          make helm-push
          make clean
